### ISSUE TITLE
Venom Page Item Limit

### ISSUE THREAD

**Issue by Wildpig954** [123Venom/context.trailer.mod#1]
Hi sorry to report this, I have found a way to break the "Next Page" of either "Movie lists" or "TV shows list".
before todays update V6.5.6 I had tried to increase the page item limit to max 40 and found when i loaded up a list the "Next Page (2)" was missing(this is persistent), so I dialed it back to Page Item Limit of 32, but the next page was still missing. 
load up other lists that haven't been loaded with the Page Item Limit set to 40 and they are ok I have the "Next Page".

I allowed the update to V6.5.6 and my next page item was back...until i started mucking with the settings again. My movie lists are ok, but me TV lists are limited to 32 with no next page.

Operating System: Android
Device: Nvidia Shield
Version of Kodi: 19.4
Skin: Xonfluence
Version of Venom add-on: 6.5.6
Country: Australia
Debrid services in use: Premiumize
[kodi.log](https://github.com/123Venom/context.trailer.mod/files/8458715/kodi.log)

I'm not sure if the logs will help
Thanks

**Comment by 123Venom** [comment]
Why was this Venom addon issue reported in `context.trailer.mod` issues?

I bumped page item limit to 40 in Venom and reviewed a few lists of Movies and TV Shows and did not find a case where Next Page was missing.  You didn't give a specific list this occurs on or are you seeing it on all?  Also TMDb lists do not respect this setting and will not be made to do so.  TMDb limits their request to 20 items so to do a 40 item page I'd have to dbl up requests and I'm not interesting in doing that, just mentioning it.

**Comment by TapMeDead** [comment]
@Wildpig954 Could you post which genre or where exactly you are getting this issue please?
I am set at 60 per page, never see the "next page" button missing, unless there are too few items left in the genre and I use "hide watched" for example. If a genre or search only has 31 items, of course the button wont show if yo are at 40 items :)

**Comment by Wildpig954** [comment]
Oh bugger, sorry I have no idea how that happened. 
Do you want me to recreate this in the right area?
The problem I had was with displaying Trakt lists.  I have 5 lists in the TV category and 2 lists in movies. 
![7B0E39B0-0D40-4D24-A9B0-54F9660F3C50](https://user-images.githubusercontent.com/91895648/162635622-e623dddf-9609-4e3d-9e81-3cf69591744c.jpeg)

**Comment by 123Venom** [comment]
Na leave the issue here and we'll just finish up for this time but watch for it in the future.

These your own personal Trakt lists?  I only have a couple myself to test and sadly only couple items in each.  I do have a large Collection list of movies and when I set the page item limit to 40 there it works fine but I also use Trakt pagination setting.  I have some liked lists with large items and those also worked fine.  If it's your personal list I'd have to build a healthy one to test it and see if it's personal lists doing this.

So next we need:
personal lits only doing this?
how many items in the lists in question?

**Comment by Wildpig954** [comment]
Hi, It looks like it is only personal lists that are doing this.
My list has 166 items.
I did some testing to see if I can cause the issue for other items(not personal lists) and couldn’t.
I think the issue is related to the way I am accessing the list, right now I have increased the display items to 60 per page, then go to my tv list and it’s got the Next Page option(I couldn’t do this, even when I changed the display items back to 24), if I bring up the list via “favourites” the list is missing the “Next Page” button again.

**Comment by 123Venom** [comment]
I can't answer you on the favorites handling of this.  I just added one of my movie liked lists, `IMDb: Top Rated Movies-justin` to favorites and when loading from there it was fine and Next Page was visible.  Afraid I can't help you beyond this.

**Comment by Wildpig954** [comment]
Thanks for your assistance.
Is it possible to remove or increase the items per page limit?

**Comment by TapMeDead** [comment]
@Wildpig954 There is another way, you can go to Trakt settings and disable Pagination near the bottom of that page.

**Comment by Wildpig954** [comment]
Thanks TapMeDead
I’ll check that out tonight

Sent from my iPhone

On 11 Apr 2022, at 8:26 am, TapMeDead ***@***.***> wrote:

﻿

@Wildpig954<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWildpig954&data=04%7C01%7C%7C4d5ca97740f54e430d0e08da1b412c4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637852263984804822%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FctbFPOtU6PnUSjALGJO4sTMnhybBeFMA4qOyvHVVAU%3D&reserved=0> There is another way, you can go to Trakt settings and disable Pagination near the bottom of that page.

**Comment by Wildpig954** [comment]
@TapMeDead 
That for pointing out the setting for Pagination, that is exactly what I was trying to achieve.
Legend 👍
